### ISSUE TITLE
Existing issue 1

### ISSUE THREAD

**Issue by njkatariya1607** [meher421/fictional-pancake#1]
# issue 1 Flash screen timing should be not more than 3 seconds , its talking too long to open the home screen .
# issue 2 admin doesnt show status  up down steady and closed , it only shows numbers from 1 to 10 for both status and market status.
# issue 3 USD entry doesnt get accepted .
# issue 4 when we submit the entries it doesnt get posted on the home screen

**Comment by meher421** [comment]
Issue 1: Splash screen will remain for atleast 3 seconds for the first time launch only.If it goes beyond 3 seconds for the time,then its because application is fetching  data in the background. If its not the first launch its not need to remain 3 seconds as its annoying to the user.

**Comment by meher421** [comment]
Issue 3: USD entry is getting accepted in the latest apk.Pls check

**Comment by meher421** [comment]
Issue 4: This behavior proper as it is seen only to the admin.

**Comment by meher421** [comment]
raise separate issue for issue 2 to track. Closing this issue as it has multiple issues
